# Generated by Django 2.2 on 2019-10-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=8)),
                ('last_name', models.CharField(max_length=8)),
            ],
        ),
    ]
