<<<<<<< HEAD
# Generated by Django 2.2 on 2019-10-15 21:26

from django.db import migrations, models
=======
# Generated by Django 2.2 on 2019-10-17 19:54

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=8)),
                ('last_name', models.CharField(max_length=8)),
=======
                ('judge_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('project_title', models.CharField(max_length=500)),
                ('project_category', models.CharField(max_length=100)),
                ('avg_score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('z_score', models.FloatField()),
                ('scaled_score', models.FloatField()),
                ('scaled_rank', models.FloatField()),
                ('scaled_z', models.FloatField()),
                ('isef_score', models.FloatField()),
                ('isef_rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=100)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.Project')),
            ],
        ),
        migrations.CreateModel(
            name='judge_assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_score', models.IntegerField()),
                ('plan_score', models.IntegerField()),
                ('action_score', models.IntegerField()),
                ('result_analysis_score', models.IntegerField()),
                ('communication_score', models.IntegerField()),
                ('raw_score', models.IntegerField()),
                ('judge_id_f', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.Judge')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.Project')),
>>>>>>> master
            ],
        ),
    ]
