# Generated by Django 2.2 on 2019-11-05 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('judge_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('project_title', models.CharField(max_length=500)),
                ('project_category', models.CharField(max_length=100)),
                ('avg_score', models.FloatField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('z_score', models.FloatField(null=True)),
                ('scaled_score', models.FloatField(null=True)),
                ('scaled_rank', models.FloatField(null=True)),
                ('scaled_z', models.FloatField(null=True)),
                ('isef_score', models.FloatField(null=True)),
                ('isef_rank', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=100)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Judge_Assignment',
            fields=[
                ('ja_id', models.IntegerField(primary_key=True, serialize=False)),
                ('goal_score', models.IntegerField(null=True)),
                ('plan_score', models.IntegerField(null=True)),
                ('action_score', models.IntegerField(null=True)),
                ('result_analysis_score', models.IntegerField(null=True)),
                ('communication_score', models.IntegerField(null=True)),
                ('raw_score', models.IntegerField(null=True)),
                ('judge_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.Judge')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.Project')),
            ],
        ),
    ]
