# Generated by Django 2.2 on 2019-11-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge_assignment',
            name='action_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='judge_assignment',
            name='communication_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='judge_assignment',
            name='goal_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='judge_assignment',
            name='plan_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='judge_assignment',
            name='raw_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='judge_assignment',
            name='result_analysis_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='avg_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='isef_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='isef_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='scaled_rank',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='scaled_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='scaled_z',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='z_score',
            field=models.FloatField(null=True),
        ),
    ]
