# Generated by Django 2.2 on 2019-11-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge_assignment',
            name='rank',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='judge_assignment',
            name='z_score',
            field=models.FloatField(null=True),
        ),
    ]
