# Generated by Django 2.2 on 2019-11-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_auto_20191118_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg_01',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='avg_01_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fair_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='z_score_rank',
            field=models.IntegerField(null=True),
        ),
    ]
